/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    BackgroundSection: typeof import('./src/components/team/BackgroundSection.vue')['default']
    CoreSkillsSection: typeof import('./src/components/team/CoreSkillsSection.vue')['default']
    EmptyPlaceholder: typeof import('./src/components/shared/EmptyPlaceholder.vue')['default']
    EventsSection: typeof import('./src/components/knowledge/EventsSection.vue')['default']
    HeroSection: typeof import('./src/components/hero/HeroSection.vue')['default']
    IntroCard: typeof import('./src/components/team/IntroCard.vue')['default']
    MemberCard: typeof import('./src/components/members/MemberCard.vue')['default']
    MembersSection: typeof import('./src/components/members/MembersSection.vue')['default']
    MonitoringReportSection: typeof import('./src/components/project-analysis/MonitoringReportSection.vue')['default']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NModal: typeof import('naive-ui')['NModal']
    OrgChartSection: typeof import('./src/components/orgchart/OrgChartSection.vue')['default']
    OrgTreeNode: typeof import('./src/components/orgchart/OrgTreeNode.vue')['default']
    ProjectAnalysisSection: typeof import('./src/components/project-analysis/ProjectAnalysisSection.vue')['default']
    ResearchTopicsSection: typeof import('./src/components/knowledge/ResearchTopicsSection.vue')['default']
    ResponsibilitiesSection: typeof import('./src/components/team/ResponsibilitiesSection.vue')['default']
    ResponsibilityCard: typeof import('./src/components/team/ResponsibilityCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionTitle: typeof import('./src/components/shared/SectionTitle.vue')['default']
    ShowcaseCard: typeof import('./src/components/showcase/ShowcaseCard.vue')['default']
    ShowcaseSection: typeof import('./src/components/showcase/ShowcaseSection.vue')['default']
    TeamIntroSection: typeof import('./src/components/team/TeamIntroSection.vue')['default']
    TeamPageLayout: typeof import('./src/components/layout/TeamPageLayout.vue')['default']
    TechSection: typeof import('./src/components/tech/TechSection.vue')['default']
    TimelineSection: typeof import('./src/components/team/TimelineSection.vue')['default']
    TopicsIframeSection: typeof import('./src/components/knowledge/TopicsIframeSection.vue')['default']
    TopicsSection: typeof import('./src/components/knowledge/TopicsSection.vue')['default']
    TrainingSection: typeof import('./src/components/knowledge/TrainingSection.vue')['default']
    WorkflowImagesSection: typeof import('./src/components/team/WorkflowImagesSection.vue')['default']
    WorkingGroupsSection: typeof import('./src/components/team/WorkingGroupsSection.vue')['default']
    WorkModeSection: typeof import('./src/components/workmode/WorkModeSection.vue')['default']
  }
}
