/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    AppHeader: typeof import('./src/components/layout/AppHeader.vue')['default']
    DepartmentSection: typeof import('./src/components/department/DepartmentSection.vue')['default']
    EventsSection: typeof import('./src/components/knowledge/EventsSection.vue')['default']
    HeroSection: typeof import('./src/components/hero/HeroSection.vue')['default']
    IntroCard: typeof import('./src/components/department/IntroCard.vue')['default']
    MemberCard: typeof import('./src/components/members/MemberCard.vue')['default']
    MembersSection: typeof import('./src/components/members/MembersSection.vue')['default']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NModal: typeof import('naive-ui')['NModal']
    ResponsibilityCard: typeof import('./src/components/department/ResponsibilityCard.vue')['default']
    SectionTitle: typeof import('./src/components/shared/SectionTitle.vue')['default']
    TeamSection: typeof import('./src/components/department/TeamSection.vue')['default']
    TechSection: typeof import('./src/components/tech/TechSection.vue')['default']
    TopicsSection: typeof import('./src/components/knowledge/TopicsSection.vue')['default']
    TrainingSection: typeof import('./src/components/knowledge/TrainingSection.vue')['default']
    WorkModeSection: typeof import('./src/components/workmode/WorkModeSection.vue')['default']
  }
}
